[package]
name = "bp-perm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bulletproofs = {version = "4.0.0" }
merlin = {version="^3" }
curve25519-dalek-ng = {version = "^4"}

